FROM mcr.microsoft.com/dotnet/sdk:7.0
WORKDIR .

COPY . ./
RUN dotnet restore
RUN dotnet build
RUN dotnet publish -c Release -o out

# Path: dockerfile
FROM mcr.microsoft.com/dotnet/aspnet:7.0
WORKDIR .
COPY --from=build ./ .
ENTRYPOINT [ "dotnet", "TodoApi.dll"]


